from dataclasses import dataclass
from typing import BinaryIO, Protocol


@dataclass(frozen=True)
class StoredObject:
    size_bytes: int
    sha256: str


class ArtifactStore(Protocol):
    def put(self, key: str, source: BinaryIO) -> StoredObject: ...
    def get(self, key: str) -> BinaryIO: ...
    def delete(self, key: str) -> None: ...
    def exists(self, key: str) -> bool: ...
    def metadata(self, key: str) -> StoredObject: ...
    def ready(self) -> None: ...
