"""identity_tenancy

Revision ID: 0005_identity_tenancy
Revises: 0004_governance_reports
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0005_identity_tenancy"
down_revision = "0004_governance_reports"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="ACTIVE", nullable=False),
        sa.Column(
            "retention_policy",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default='{"source":"manual","synthetic":"manual","model":"manual","report":"manual"}',
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','DISABLED')", name=op.f("ck_organizations_organization_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("slug", name=op.f("uq_organizations_slug")),
    )
    op.execute(
        "INSERT INTO organizations (id,name,slug) VALUES ('00000000-0000-4000-8000-000000000001','Development workspace','development')"
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("issuer", sa.String(length=512), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="ACTIVE", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('ACTIVE','DISABLED')", name=op.f("ck_users_user_status")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("issuer", "subject", name="uq_users_external_identity"),
    )
    op.create_table(
        "login_sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("csrf_token", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_login_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("token_hash", name=op.f("pk_login_sessions")),
    )
    op.create_index(
        op.f("ix_login_sessions_expires_at"), "login_sessions", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_login_sessions_user_id"), "login_sessions", ["user_id"], unique=False)
    op.create_table(
        "organization_memberships",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="ACTIVE", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('OWNER','EDITOR','VIEWER')",
            name=op.f("ck_organization_memberships_membership_role"),
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','REMOVED')",
            name=op.f("ck_organization_memberships_membership_status"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_organization_memberships_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_organization_memberships_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_memberships")),
        sa.UniqueConstraint("organization_id", "user_id", name="uq_membership_org_user"),
    )
    op.create_index(
        op.f("ix_organization_memberships_organization_id"),
        "organization_memberships",
        ["organization_id"],
        unique=False,
    )
    op.add_column("audit_events", sa.Column("user_id", sa.Uuid(), nullable=True))
    op.add_column("audit_events", sa.Column("organization_id", sa.Uuid(), nullable=True))
    op.add_column("audit_events", sa.Column("request_id", sa.String(length=64), nullable=True))
    op.create_index(
        op.f("ix_audit_events_organization_id"), "audit_events", ["organization_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_audit_events_user_id_users"),
        "audit_events",
        "users",
        ["user_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_audit_events_organization_id_organizations"),
        "audit_events",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.add_column(
        "projects",
        sa.Column(
            "organization_id",
            sa.Uuid(),
            server_default="00000000-0000-4000-8000-000000000001",
            nullable=False,
        ),
    )
    op.add_column(
        "projects",
        sa.Column("deletion_state", sa.String(length=24), server_default="ACTIVE", nullable=False),
    )
    op.add_column(
        "projects", sa.Column("deletion_requested_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("projects", sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(
        op.f("ix_projects_organization_id"), "projects", ["organization_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_projects_organization_id_organizations"),
        "projects",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_check_constraint(
        op.f("ck_projects_project_deletion_state"),
        "projects",
        "deletion_state IN ('ACTIVE','DELETION_REQUESTED','PURGING','DELETED')",
    )
    op.drop_constraint(op.f("ck_audit_events_audit_actor"), "audit_events", type_="check")
    op.create_check_constraint(
        op.f("ck_audit_events_audit_actor"),
        "audit_events",
        "actor IN ('anonymous','system','worker','user')",
    )
    # One-time migration backfill; ordinary application updates remain prohibited.
    op.execute("ALTER TABLE audit_events DISABLE TRIGGER audit_immutable")
    op.execute("UPDATE audit_events SET organization_id='00000000-0000-4000-8000-000000000001'")
    op.execute("ALTER TABLE audit_events ENABLE TRIGGER audit_immutable")
    op.execute("""CREATE FUNCTION immutable_project_organization() RETURNS trigger AS $$
    BEGIN
      IF NEW.organization_id IS DISTINCT FROM OLD.organization_id THEN
        RAISE EXCEPTION 'Project organization cannot be reassigned';
      END IF;
      RETURN NEW;
    END; $$ LANGUAGE plpgsql""")
    op.execute(
        "CREATE TRIGGER project_organization_immutable BEFORE UPDATE ON projects FOR EACH ROW EXECUTE FUNCTION immutable_project_organization()"
    )


def downgrade():
    connection = op.get_bind()
    if connection.execute(
        sa.text(
            "SELECT EXISTS(SELECT 1 FROM users) OR EXISTS(SELECT 1 FROM organizations WHERE slug <> 'development') OR EXISTS(SELECT 1 FROM projects WHERE deletion_state <> 'ACTIVE')"
        )
    ).scalar_one():
        raise RuntimeError(
            "Refusing downgrade that would discard identity or lifecycle data; restore a verified backup"
        )
    op.execute("DROP TRIGGER project_organization_immutable ON projects")
    op.execute("DROP FUNCTION immutable_project_organization()")
    op.drop_constraint(op.f("ck_projects_project_deletion_state"), "projects", type_="check")
    op.drop_constraint(op.f("ck_audit_events_audit_actor"), "audit_events", type_="check")
    op.create_check_constraint(
        op.f("ck_audit_events_audit_actor"),
        "audit_events",
        "actor IN ('anonymous','system','worker')",
    )
    op.drop_constraint(
        op.f("fk_projects_organization_id_organizations"), "projects", type_="foreignkey"
    )
    op.drop_index(op.f("ix_projects_organization_id"), table_name="projects")
    op.drop_column("projects", "purged_at")
    op.drop_column("projects", "deletion_requested_at")
    op.drop_column("projects", "deletion_state")
    op.drop_column("projects", "organization_id")
    op.drop_constraint(
        op.f("fk_audit_events_organization_id_organizations"), "audit_events", type_="foreignkey"
    )
    op.drop_constraint(op.f("fk_audit_events_user_id_users"), "audit_events", type_="foreignkey")
    op.drop_index(op.f("ix_audit_events_organization_id"), table_name="audit_events")
    op.drop_column("audit_events", "request_id")
    op.drop_column("audit_events", "organization_id")
    op.drop_column("audit_events", "user_id")
    op.drop_index(
        op.f("ix_organization_memberships_organization_id"), table_name="organization_memberships"
    )
    op.drop_table("organization_memberships")
    op.drop_index(op.f("ix_login_sessions_user_id"), table_name="login_sessions")
    op.drop_index(op.f("ix_login_sessions_expires_at"), table_name="login_sessions")
    op.drop_table("login_sessions")
    op.drop_table("users")
    op.drop_table("organizations")
    # ### end Alembic commands ###
